Go rook bump to 0.0.5
Rookout/microservices-demo pull request #33
Opened 2021-11-28 07:39 UTC by ElDuderinos

Aligning with proper go get modules and using an updated version.
Not tested yet.

2021-11-29 10:41 UTC, ElDuderinos commented
/jira open task

2021-11-29 11:33 UTC, dan505512 submitted a review, later dismissed

2021-11-30 08:00 UTC, lirook commented
Tried to run "make build", got this:
```
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DataExtractor.cpp.o): in function `llvm::format_object<unsigned long, char const*>::snprint(char*, unsigned int) const':
#13 22.69 DataExtractor.cpp:(.text._ZNK4llvm13format_objectIJmPKcEE7snprintEPcj[_ZNK4llvm13format_objectIJmPKcEE7snprintEPcj]+0x27): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DataExtractor.cpp.o): in function `llvm::format_object<unsigned long, unsigned long, unsigned long>::snprint(char*, unsigned int) const':
#13 22.69 DataExtractor.cpp:(.text._ZNK4llvm13format_objectIJmmmEE7snprintEPcj[_ZNK4llvm13format_objectIJmmmEE7snprintEPcj]+0x27): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(ItaniumManglingCanonicalizer.cpp.o): in function `llvm::itanium_demangle::FloatLiteralImpl<long double>::printLeft(llvm::itanium_demangle::OutputStream&) const':
#13 22.69 ItaniumManglingCanonicalizer.cpp:(.text._ZNK4llvm16itanium_demangle16FloatLiteralImplIeE9printLeftERNS0_12OutputStreamE[_ZNK4llvm16itanium_demangle16FloatLiteralImplIeE9printLeftERNS0_12OutputStreamE]+0xb4): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(ItaniumManglingCanonicalizer.cpp.o): in function `llvm::itanium_demangle::FloatLiteralImpl<double>::printLeft(llvm::itanium_demangle::OutputStream&) const':
#13 22.69 ItaniumManglingCanonicalizer.cpp:(.text._ZNK4llvm16itanium_demangle16FloatLiteralImplIdE9printLeftERNS0_12OutputStreamE[_ZNK4llvm16itanium_demangle16FloatLiteralImplIdE9printLeftERNS0_12OutputStreamE]+0xa8): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(ItaniumManglingCanonicalizer.cpp.o): in function `llvm::itanium_demangle::FloatLiteralImpl<float>::printLeft(llvm::itanium_demangle::OutputStream&) const':
#13 22.69 ItaniumManglingCanonicalizer.cpp:(.text._ZNK4llvm16itanium_demangle16FloatLiteralImplIfE9printLeftERNS0_12OutputStreamE[_ZNK4llvm16itanium_demangle16FloatLiteralImplIfE9printLeftERNS0_12OutputStreamE]+0xb0): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(PrettyStackTrace.cpp.o): in function `llvm::PrettyStackTraceFormat::PrettyStackTraceFormat(char const*, ...)':
#13 22.69 PrettyStackTrace.cpp:(.text._ZN4llvm22PrettyStackTraceFormatC2EPKcz+0xe3): undefined reference to `__vsnprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: PrettyStackTrace.cpp:(.text._ZN4llvm22PrettyStackTraceFormatC2EPKcz+0x172): undefined reference to `__vsnprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(SHA1.cpp.o): in function `llvm::SHA1::hash(llvm::ArrayRef<unsigned char>)':
#13 22.69 SHA1.cpp:(.text._ZN4llvm4SHA14hashENS_8ArrayRefIhEE+0x5f): undefined reference to `__memcpy_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(regerror.c.o): in function `llvm_regerror':
#13 22.69 regerror.c:(.text.llvm_regerror+0x104): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(InlineAsm.cpp.o): in function `llvm::hash_code llvm::hash_combine<llvm::StringRef, llvm::StringRef, bool, bool, llvm::InlineAsm::AsmDialect, llvm::FunctionType*>(llvm::StringRef const&, llvm::StringRef const&, bool const&, bool const&, llvm::InlineAsm::AsmDialect const&, llvm::FunctionType* const&)':
#13 22.69 InlineAsm.cpp:(.text._ZN4llvm12hash_combineIJNS_9StringRefES1_bbNS_9InlineAsm10AsmDialectEPNS_12FunctionTypeEEEENS_9hash_codeEDpRKT_[_ZN4llvm12hash_combineIJNS_9StringRefES1_bbNS_9InlineAsm10AsmDialectEPNS_12FunctionTypeEEEENS_9hash_codeEDpRKT_]+0x184): undefined reference to `__memcpy_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: InlineAsm.cpp:(.text._ZN4llvm12hash_combineIJNS_9StringRefES1_bbNS_9InlineAsm10AsmDialectEPNS_12FunctionTypeEEEENS_9hash_codeEDpRKT_[_ZN4llvm12hash_combineIJNS_9StringRefES1_bbNS_9InlineAsm10AsmDialectEPNS_12FunctionTypeEEEENS_9hash_codeEDpRKT_]+0x213): undefined reference to `__memcpy_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned int, unsigned long>::snprint(char*, unsigned int) const':
#13 22.69 DWARFDebugAddr.cpp:(.text._ZNK4llvm13format_objectIJjmEE7snprintEPcj[_ZNK4llvm13format_objectIJjmEE7snprintEPcj]+0x27): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned long, unsigned char, unsigned char>::snprint(char*, unsigned int) const':
#13 22.69 DWARFDebugAddr.cpp:(.text._ZNK4llvm13format_objectIJmhhEE7snprintEPcj[_ZNK4llvm13format_objectIJmhhEE7snprintEPcj]+0x2b): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned long, unsigned short>::snprint(char*, unsigned int) const':
#13 22.69 DWARFDebugAddr.cpp:(.text._ZNK4llvm13format_objectIJmtEE7snprintEPcj[_ZNK4llvm13format_objectIJmtEE7snprintEPcj]+0x29): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned long, unsigned long, unsigned char>::snprint(char*, unsigned int) const':
#13 22.69 DWARFDebugAddr.cpp:(.text._ZNK4llvm13format_objectIJmmhEE7snprintEPcj[_ZNK4llvm13format_objectIJmmhEE7snprintEPcj]+0x29): undefined reference to `__snprintf_chk'
#13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned long, unsigned char>::snprint(char*, unsigned int) const':
#13 22.69 DWARFDebugAddr.cpp:(.text._Z [...]

2021-11-30 08:02 UTC, ElDuderinos commented
> Tried to run "make build", got this:
> 
> ```
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DataExtractor.cpp.o): in function `llvm::format_object<unsigned long, char const*>::snprint(char*, unsigned int) const':
> #13 22.69 DataExtractor.cpp:(.text._ZNK4llvm13format_objectIJmPKcEE7snprintEPcj[_ZNK4llvm13format_objectIJmPKcEE7snprintEPcj]+0x27): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DataExtractor.cpp.o): in function `llvm::format_object<unsigned long, unsigned long, unsigned long>::snprint(char*, unsigned int) const':
> #13 22.69 DataExtractor.cpp:(.text._ZNK4llvm13format_objectIJmmmEE7snprintEPcj[_ZNK4llvm13format_objectIJmmmEE7snprintEPcj]+0x27): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(ItaniumManglingCanonicalizer.cpp.o): in function `llvm::itanium_demangle::FloatLiteralImpl<long double>::printLeft(llvm::itanium_demangle::OutputStream&) const':
> #13 22.69 ItaniumManglingCanonicalizer.cpp:(.text._ZNK4llvm16itanium_demangle16FloatLiteralImplIeE9printLeftERNS0_12OutputStreamE[_ZNK4llvm16itanium_demangle16FloatLiteralImplIeE9printLeftERNS0_12OutputStreamE]+0xb4): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(ItaniumManglingCanonicalizer.cpp.o): in function `llvm::itanium_demangle::FloatLiteralImpl<double>::printLeft(llvm::itanium_demangle::OutputStream&) const':
> #13 22.69 ItaniumManglingCanonicalizer.cpp:(.text._ZNK4llvm16itanium_demangle16FloatLiteralImplIdE9printLeftERNS0_12OutputStreamE[_ZNK4llvm16itanium_demangle16FloatLiteralImplIdE9printLeftERNS0_12OutputStreamE]+0xa8): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(ItaniumManglingCanonicalizer.cpp.o): in function `llvm::itanium_demangle::FloatLiteralImpl<float>::printLeft(llvm::itanium_demangle::OutputStream&) const':
> #13 22.69 ItaniumManglingCanonicalizer.cpp:(.text._ZNK4llvm16itanium_demangle16FloatLiteralImplIfE9printLeftERNS0_12OutputStreamE[_ZNK4llvm16itanium_demangle16FloatLiteralImplIfE9printLeftERNS0_12OutputStreamE]+0xb0): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(PrettyStackTrace.cpp.o): in function `llvm::PrettyStackTraceFormat::PrettyStackTraceFormat(char const*, ...)':
> #13 22.69 PrettyStackTrace.cpp:(.text._ZN4llvm22PrettyStackTraceFormatC2EPKcz+0xe3): undefined reference to `__vsnprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: PrettyStackTrace.cpp:(.text._ZN4llvm22PrettyStackTraceFormatC2EPKcz+0x172): undefined reference to `__vsnprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(SHA1.cpp.o): in function `llvm::SHA1::hash(llvm::ArrayRef<unsigned char>)':
> #13 22.69 SHA1.cpp:(.text._ZN4llvm4SHA14hashENS_8ArrayRefIhEE+0x5f): undefined reference to `__memcpy_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(regerror.c.o): in function `llvm_regerror':
> #13 22.69 regerror.c:(.text.llvm_regerror+0x104): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(InlineAsm.cpp.o): in function `llvm::hash_code llvm::hash_combine<llvm::StringRef, llvm::StringRef, bool, bool, llvm::InlineAsm::AsmDialect, llvm::FunctionType*>(llvm::StringRef const&, llvm::StringRef const&, bool const&, bool const&, llvm::InlineAsm::AsmDialect const&, llvm::FunctionType* const&)':
> #13 22.69 InlineAsm.cpp:(.text._ZN4llvm12hash_combineIJNS_9StringRefES1_bbNS_9InlineAsm10AsmDialectEPNS_12FunctionTypeEEEENS_9hash_codeEDpRKT_[_ZN4llvm12hash_combineIJNS_9StringRefES1_bbNS_9InlineAsm10AsmDialectEPNS_12FunctionTypeEEEENS_9hash_codeEDpRKT_]+0x184): undefined reference to `__memcpy_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: InlineAsm.cpp:(.text._ZN4llvm12hash_combineIJNS_9StringRefES1_bbNS_9InlineAsm10AsmDialectEPNS_12FunctionTypeEEEENS_9hash_codeEDpRKT_[_ZN4llvm12hash_combineIJNS_9StringRefES1_bbNS_9InlineAsm10AsmDialectEPNS_12FunctionTypeEEEENS_9hash_codeEDpRKT_]+0x213): undefined reference to `__memcpy_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned int, unsigned long>::snprint(char*, unsigned int) const':
> #13 22.69 DWARFDebugAddr.cpp:(.text._ZNK4llvm13format_objectIJjmEE7snprintEPcj[_ZNK4llvm13format_objectIJjmEE7snprintEPcj]+0x27): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned long, unsigned char, unsigned char>::snprint(char*, unsigned int) const':
> #13 22.69 DWARFDebugAddr.cpp:(.text._ZNK4llvm13format_objectIJmhhEE7snprintEPcj[_ZNK4llvm13format_objectIJmhhEE7snprintEPcj]+0x2b): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned long, unsigned short>::snprint(char*, unsigned int) const':
> #13 22.69 DWARFDebugAddr.cpp:(.text._ZNK4llvm13format_objectIJmtEE7snprintEPcj[_ZNK4llvm13format_objectIJmtEE7snprintEPcj]+0x29): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned long, unsigned long, unsigned char>::snprint(char*, unsigned int) const':
> #13 22.69 DWARFDebugAddr.cpp:(.text._ZNK4llvm13format_objectIJmmhEE7snprintEPcj[_ZNK4llvm13format_objectIJmmhEE7snprintEPcj]+0x29): undefined reference to `__snprintf_chk'
> #13 22.69 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /go/pkg/mod/github.com/!rookout/!go!rook@v0.0.5/pkg/services/instrumentation/hooker/libhook_lib_pack_ubuntu20.a(DWARFDebugAddr.cpp.o): in function `llvm::format_object<unsigned long, unsigned char>::snprint(ch [...]

2021-11-30 09:22 UTC, lirook requested changes

2021-11-30 09:22 UTC, lirook commented on src/productcatalogservice/Dockerfile
>  RUN go build -gcflags='-N -l' -o /go/bin/productcatalogservice .
```suggestion
RUN go build -tags=${GOROOK_OS_TAG} -gcflags='-N -l' -o /go/bin/productcatalogservice .
```

2021-11-30 09:26 UTC, lirook requested changes

2021-11-30 09:26 UTC, lirook commented on src/shippingservice/Dockerfile
>  RUN go build -gcflags='-N -l' -o /go/bin/shippingservice
```suggestion
RUN go build -tags=${GOROOK_OS_TAG} -gcflags='-N -l' -o /go/bin/shippingservice
```

2021-12-01 06:23 UTC, ElDuderinos commented on src/productcatalogservice/Dockerfile
>  RUN go build -gcflags='-N -l' -o /go/bin/productcatalogservice .
yep, I missed those

2021-12-01 13:57 UTC, lirook approved these changes

2021-12-02 11:09 UTC, merged